# fly.toml app configuration file generated for foo-still-firefly-4401 on 2024-10-16T13:52:27+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'foo-still-firefly-4401'
primary_region = 'fra'

[build.args]
  NODE_VERSION="22.9.0"

[deploy]
  strategy = "immediate"

[env]
  DEBUG = "indiekit:*,-indiekit:request,indiekit-store:*"

[http_service]
  auto_start_machines = true
  auto_stop_machines = 'stop'
  force_https = true
  internal_port = 3000
  min_machines_running = 0
  processes = ['app']

[[restart]]
  policy = 'never'
  retries = 10
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
