# fly.toml app configuration file generated for giacomodebidda-indiekit on 2024-10-17T11:11:43+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'giacomodebidda-indiekit'
primary_region = 'fra'
kill_timeout = 180

[build]

[deploy]
  strategy = 'immediate'

[env]
  DEBUG = 'indiekit:*,-indiekit:request,indiekit-store:*'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[restart]]
  policy = 'never'
  retries = 10
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
